name: Test Workflow

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:   # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 23f2004076@ds.study.iitm.ac.in
        run: echo "Hello, world!"
