name: CI with Cache

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache dependencies
        id: prime-cache-550a115
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-550a115

      - name: Echo cache result
        run: |
          echo "Cache hit status: ${{ steps.prime-cache-550a115.outputs.cache-hit }}"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
